## 1. Create

In [1]:
import numpy as np

In [2]:
data = np.random.rand(2,3,4)

In [3]:
data

array([[[0.48691009, 0.72516045, 0.85858775, 0.63189174],
        [0.26870034, 0.51495958, 0.84673108, 0.52405427],
        [0.03276913, 0.43658797, 0.57680717, 0.23317517]],

       [[0.07097066, 0.48204246, 0.64944359, 0.61875226],
        [0.43782973, 0.91585801, 0.03915616, 0.12415983],
        [0.99777666, 0.25101337, 0.49544651, 0.89841225]]])

In [4]:
zeros = np.zeros((2,2,2))

In [5]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
full = np.full((2,2,2),10)

In [7]:
full

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [8]:
ones = np.ones((2,2,2))

In [9]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
myArray = np.array([[[1,2,3],[1,2,9]]])

In [11]:
myArray

array([[[1, 2, 3],
        [1, 2, 9]]])

In [12]:
type(myArray)

numpy.ndarray

## 2. Read

In [13]:
## attributes
shape = data.shape
size = data.size
types = data.dtype
types

dtype('float64')

In [14]:
## slicing
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singleEval = data[0][0][0]

## 3.Update

In [15]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [16]:
list2

array([0.93884636, 0.57234629, 0.46464761, 0.6846945 , 0.1389743 ,
       0.35437754, 0.6555643 , 0.09565919, 0.35972836, 0.85500072])

In [17]:
# Basic Math

In [18]:
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
mult = np.multiply(list1,list2)
div = np.divide(list1,list2)
dot = np.dot(list1,list2)

In [19]:
dot

3.572920816764839

In [20]:
## Stat functions

In [23]:
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [24]:
data.sort()
data

array([[[0.48691009, 0.63189174, 0.72516045, 0.85858775],
        [0.26870034, 0.51495958, 0.52405427, 0.84673108],
        [0.03276913, 0.23317517, 0.43658797, 0.57680717]],

       [[0.07097066, 0.48204246, 0.61875226, 0.64944359],
        [0.03915616, 0.12415983, 0.43782973, 0.91585801],
        [0.25101337, 0.49544651, 0.89841225, 0.99777666]]])

In [25]:
data = data.reshape(2,2,-1)
data.shape

(2, 2, 6)

In [26]:
zeroes = np.zeros(8)
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [33]:
np.insert(zeroes, 2, 9)

array([0., 0., 9., 0., 0., 0., 0., 0., 0., 3., 4.])

## 4. Delete

In [29]:
np.delete(data, 0, axis=1)

array([[[0.52405427, 0.84673108, 0.03276913, 0.23317517, 0.43658797,
         0.57680717]],

       [[0.43782973, 0.91585801, 0.25101337, 0.49544651, 0.89841225,
         0.99777666]]])

In [30]:
np.save("my array", data)

In [31]:
test = np.load("my array.npy")